# Copyright 2022 Red Hat, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: Template
metadata:
  name: exporter-${DB_NAME}
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: exporter-${DB_NAME}
  spec:
    envName: ${ENV_NAME}
    testing:
      iqePlugin: ccx
    jobs:
    - name: instance
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}
      backoffLimit: 1 # Clowder doesn't support this setting as a parameter - https://coreos.slack.com/archives/CCRND57FW/p1657620480174029?thread_ts=1657619229.653889&cid=CCRND57FW
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command:
          - ./insights-results-aggregator-exporter
        args:
          - "-output=${OUTPUT}"
          - "-metadata=true"
          - "-ignore-tables=${TABLES_TO_IGNORE}"
        restartPolicy: Never
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        env:
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__STORAGE__DB_DRIVER
          value: postgres
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__STORAGE__PG_PARAMS
          value: sslmode=disable
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__TYPE
          value: ${S3__TYPE}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: ccx-results-exporter-s3
              key: endpoint
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__ENDPOINT_PORT
          value: ${S3__ENDPOINT_PORT}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ccx-exporter-s3-read-write
              key: aws_access_key_id
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ccx-exporter-s3-read-write
              key: aws_secret_access_key
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__USE_SSL
          value: "true"
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__BUCKET
          valueFrom:
            secretKeyRef:
              name: ccx-results-exporter-s3
              key: bucket
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__PREFIX
          value: ${DB_NAME}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__LOGGING__DEBUG
          value: "${DEBUG}"
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__LOGGING__LOG_DEVEL
          value: debug
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__SENTRY__DSN
          valueFrom:
            secretKeyRef:
              key: IRAE_SENTRY_DSN
              name: sentry-dsn
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__SENTRY__ENVIRONMENT
          value: ${ENV_NAME}
    database:
      name: ${DB_NAME}
      version: 12

parameters:
- name: CLOWDER_ENABLED
  description: Determines if this is a Clowder deployment
  value: "true"
- description: Env Name
  name: ENV_NAME
  required: true
- name: ACTIVE_DEADLINE_SECONDS
  description: The maximum duration the job can run. 
  value: "300" # 5 minutes
- name: BACKOFF_LIMIT
  description: The number of retries for a job.
  value: "1"
- name: IMAGE
  description: Image ID of the job.
  value: quay.io/cloudservices/insights-results-aggregator-exporter
- name: IMAGE_TAG
  description: The image tag.
  value: latest
- name: CPU_REQUEST
  description: Minimum amount of CPU that the job may consume.
  value: 200m
- name: MEMORY_REQUEST
  description: Minimum amount of memory that the job may consume.
  value: 5Gi
- name: CPU_LIMIT
  description: Maximum amount of CPU that the job will consume.
  value: 400m
- name: MEMORY_LIMIT
  description: Maximum amount of memory that the job will consume.
  value: 8Gi
- name: OUTPUT
  description: The exporter output (S3 or file)
  value: file
- name: TABLES_TO_IGNORE
  description: The tables to ignore
  value: ""
# Exporter configuration
- name: DEBUG
  value: "true"
- name: DB_NAME
  value: ccx-data-pipeline
  required: true
- name: S3__TYPE
  value: s3
- name: S3__ENDPOINT_PORT
  description: S3 endpoint port. Leave it empty in case you are using AWS.
- name: TEST_DATE
  description: A variable to force the job to run.
  value: 16/08/2022
